name: Fetch Weather Data

on:
    # 每天凌晨1點執行一次
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
    # 定義一個名為 fetch-weather 的工作
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
        # 使用 actions/checkout@v4 來檢出存儲庫
      - name: Checkout repository
        uses: actions/checkout@v4
        # 這裡假設 fetch_weather.py 已經存在於存儲庫中，並且會生成 weather.json 文件
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        # 安裝 requests 庫
      - name: Install requests
        run: pip install requests

        # 執行 fetch_weather.py 腳本來獲取天氣數據並生成 weather.json 文件
      - name: Run script
        run: python fetch_weather.py

        # 上傳生成的 weather.json 文件作為工作流程的工件，以便後續使用或下載
      - name: Upload weather.json
        uses: actions/upload-artifact@v4
        with:
          name: weather-json
          path: weather.json
          if-no-files-found: error